graph TD
  user[User]

  subgraph Android_App
    mainUI[Main UI]
    reminder[Reminder Module\nNotificationManager]
    scan[Scan Module\nZXing]
    db[Local Database\nRoom DB]
    apiModule[API Query Module\nOpenFoodFacts]
  end

  subgraph External_Resources
    OFF[Open Food Facts API]
  end

  user --> mainUI
  mainUI --> reminder
  mainUI --> scan
  mainUI --> db
  scan --> apiModule
  apiModule --> OFF
