graph TD
  user[User]

  subgraph Android_App
    mainUI[Main UI]
    reminder[Reminder Module (NotificationManager)]
    scan[Scan Module (ZXing)]
    db[Local Database  (Room DB)]
    apiModule[API Module (OpenFoodFacts)]
  end

  subgraph External_Resources
    OFF[Open Food Facts API]
  end

  user --> mainUI
  mainUI --> reminder
  mainUI --> scan
  mainUI --> db
  scan --> apiModule
  apiModule --> OFF
